// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace vms.entity.models
{
    public partial class Atendence
    {
        public Atendence()
        {
            AttendenceDetails = new HashSet<AttendenceDetail>();
        }

        public int AtendenceId { get; set; }
        public int? BranchId { get; set; }
        public int? Month { get; set; }
        public int? Year { get; set; }
        public int? WorkingDays { get; set; }
        public int? PayrollId { get; set; }
        public bool? IsActive { get; set; }
        public bool? Isclosed { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedTime { get; set; }

        public virtual Branch Branch { get; set; }
        public virtual Payroll Payroll { get; set; }
        public virtual ICollection<AttendenceDetail> AttendenceDetails { get; set; }
    }
}