// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace vms.entity.models
{
    public partial class Customer
    {
        public Customer()
        {
            RewardPoints = new HashSet<RewardPoint>();
            Sales = new HashSet<Sale>();
        }

        public int CustomerId { get; set; }
        public string Name { get; set; }
        public int? BranchId { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public DateTime? DateOfbirth { get; set; }
        public string Email { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedTime { get; set; }
        public bool? IsActive { get; set; }

        public virtual Branch Branch { get; set; }
        public virtual ICollection<RewardPoint> RewardPoints { get; set; }
        public virtual ICollection<Sale> Sales { get; set; }
    }
}