// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace vms.entity.models
{
    public partial class Expence
    {
        public Expence()
        {
            Payrolls = new HashSet<Payroll>();
        }

        public int ExpenceId { get; set; }
        public int? BranchId { get; set; }
        public int? ExpenceTypeId { get; set; }
        public DateTime? ExpenceDate { get; set; }
        public int? ExpencePerson { get; set; }
        public decimal? ExpenceAmount { get; set; }
        public string ExpencePurpose { get; set; }
        public int? PaymentId { get; set; }
        public bool? IsActive { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedTime { get; set; }

        public virtual Branch Branch { get; set; }
        public virtual Employe ExpencePersonNavigation { get; set; }
        public virtual ExpenceType ExpenceType { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual ICollection<Payroll> Payrolls { get; set; }
    }
}