// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace vms.entity.models
{
    public partial class Incentive
    {
        public int IncentiveId { get; set; }
        public int? EmployId { get; set; }
        public int? SalesId { get; set; }
        public decimal IncentivePoint { get; set; }
        public int? PayrollId { get; set; }
        public bool? IsActive { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedTime { get; set; }

        public virtual Employe Employ { get; set; }
        public virtual Payroll Payroll { get; set; }
        public virtual Sale Sales { get; set; }
    }
}