// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace vms.entity.models
{
    public partial class Overtime
    {
        public int OvertimeId { get; set; }
        public int? EmployId { get; set; }
        public DateTime? Date { get; set; }
        public decimal OverTimeHoure { get; set; }
        public string ReasonOfOverTime { get; set; }
        public string Remarks { get; set; }
        public int? PayrollId { get; set; }
        public bool? IsActive { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedTime { get; set; }

        public virtual Employe Employ { get; set; }
        public virtual Payroll Payroll { get; set; }
    }
}