// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace vms.entity.models
{
    public partial class PaymentMethod
    {
        public PaymentMethod()
        {
            Payments = new HashSet<Payment>();
            PurchasePayments = new HashSet<PurchasePayment>();
            SalePayments = new HashSet<SalePayment>();
        }

        public int PaymentMethodId { get; set; }
        public string Name { get; set; }
        public string Number { get; set; }
        public string Remark { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedTime { get; set; }

        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<PurchasePayment> PurchasePayments { get; set; }
        public virtual ICollection<SalePayment> SalePayments { get; set; }
    }
}