// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace vms.entity.models
{
    public partial class Payment
    {
        public Payment()
        {
            Expences = new HashSet<Expence>();
        }

        public int PaymetId { get; set; }
        public int? PaymentMethodId { get; set; }
        public decimal? AmountPaid { get; set; }
        public string TransactionId { get; set; }
        public string Remark { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? Createdtime { get; set; }

        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual ICollection<Expence> Expences { get; set; }
    }
}