// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace vms.entity.models
{
    public partial class PayrollDetail
    {
        public int PayrollDetailsId { get; set; }
        public int? PayrollId { get; set; }
        public int? SalaryId { get; set; }
        public int? EmployeId { get; set; }
        public decimal? OverTimeAmount { get; set; }
        public decimal? AdvancedAmount { get; set; }
        public decimal? IncentiveAmount { get; set; }
        public decimal? BaseSalary { get; set; }
        public decimal? PayableSalary { get; set; }

        public virtual Employe Employe { get; set; }
        public virtual Payroll Payroll { get; set; }
        public virtual Salary Salary { get; set; }
    }
}