// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace vms.entity.models
{
    public partial class Product
    {
        public Product()
        {
            Contents = new HashSet<Content>();
            ProductPrices = new HashSet<ProductPrice>();
            PurchaseDetails = new HashSet<PurchaseDetail>();
            SalesDetails = new HashSet<SalesDetail>();
            Stocks = new HashSet<Stock>();
        }

        public int ProductId { get; set; }
        public string Name { get; set; }
        public int? VatId { get; set; }
        public string ModelNo { get; set; }
        public int? MunitId { get; set; }
        public string Code { get; set; }
        public DateTime? EfectiveFrom { get; set; }
        public DateTime? EfectiveTo { get; set; }
        public bool? IsActive { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedTime { get; set; }

        public virtual MeasureUnit Munit { get; set; }
        public virtual Vat Vat { get; set; }
        public virtual ICollection<Content> Contents { get; set; }
        public virtual ICollection<ProductPrice> ProductPrices { get; set; }
        public virtual ICollection<PurchaseDetail> PurchaseDetails { get; set; }
        public virtual ICollection<SalesDetail> SalesDetails { get; set; }
        public virtual ICollection<Stock> Stocks { get; set; }
    }
}