// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace vms.entity.models
{
    public partial class PurchaseDetail
    {
        public PurchaseDetail()
        {
            Stocks = new HashSet<Stock>();
        }

        public int PurchaseDetailId { get; set; }
        public int? PurchaseId { get; set; }
        public int? ProductId { get; set; }
        public decimal? Qty { get; set; }
        public decimal? Amount { get; set; }
        public decimal? DiscountPerItem { get; set; }

        public virtual Product Product { get; set; }
        public virtual Purchase Purchase { get; set; }
        public virtual ICollection<Stock> Stocks { get; set; }
    }
}