// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace vms.entity.models
{
    public partial class RewardPoint
    {
        public int RewardPoinId { get; set; }
        public int? CustomerId { get; set; }
        public int? SalesId { get; set; }
        public decimal? PreviousPoint { get; set; }
        public int? SettingsId { get; set; }
        public decimal? Addpoint { get; set; }
        public decimal? UsePoins { get; set; }
        public decimal? Totalpoint { get; set; }
        public string Remarks { get; set; }
        public bool? IsActive { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedTime { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual Sale Sales { get; set; }
        public virtual Setting Settings { get; set; }
    }
}