// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace vms.entity.models
{
    public partial class RightsCategory
    {
        public RightsCategory()
        {
            Rights = new HashSet<Right>();
        }

        public int RightCategoryId { get; set; }
        public string RightCategoryName { get; set; }
        public string Description { get; set; }
        public bool? IsActive { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedTime { get; set; }

        public virtual ICollection<Right> Rights { get; set; }
    }
}