// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace vms.entity.models
{
    public partial class SalePayment
    {
        public int SalePaymentId { get; set; }
        public int? SaleId { get; set; }
        public int? PaymentMethodId { get; set; }
        public decimal? PaidAmount { get; set; }
        public DateTime? PaymentDate { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedTime { get; set; }

        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual Sale Sale { get; set; }
    }
}