// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace vms.entity.models
{
    public partial class SalesDetail
    {
        public int SalesDetailId { get; set; }
        public int? SaleId { get; set; }
        public int? ProductId { get; set; }
        public int? StockId { get; set; }
        public decimal? Qty { get; set; }
        public decimal? UnitPrice { get; set; }
        public decimal? DiscountPerItem { get; set; }
        public decimal? Vatpercent { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedTime { get; set; }

        public virtual Product Product { get; set; }
        public virtual Sale Sale { get; set; }
        public virtual Stock Stock { get; set; }
    }
}