// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace vms.entity.models
{
    public partial class SaleContent
    {
        public int ContentId { get; set; }
        public string Name { get; set; }
        public int? SaleId { get; set; }
        public string Url { get; set; }
        public string Remark { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedTime { get; set; }
        public bool? IsActive { get; set; }

        public virtual Sale Sale { get; set; }
    }
}