// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace vms.entity.models
{
    public partial class Stock
    {
        public Stock()
        {
            SalesDetails = new HashSet<SalesDetail>();
        }

        public int StockId { get; set; }
        public int? ProductId { get; set; }
        public decimal? InitialQty { get; set; }
        public int? PurchaseDetailId { get; set; }
        public decimal? InQty { get; set; }
        public decimal? SaleQuantity { get; set; }
        public decimal? SaleReturnQty { get; set; }
        public decimal? UsedInProductionQuantity { get; set; }
        public decimal? DamageQty { get; set; }
        public decimal? PurchaseReturnQty { get; set; }
        public decimal? CurrentStock { get; set; }
        public int? BranchId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreateTime { get; set; }
        public bool? IsActive { get; set; }

        public virtual Branch Branch { get; set; }
        public virtual User CreatedByNavigation { get; set; }
        public virtual Product Product { get; set; }
        public virtual PurchaseDetail PurchaseDetail { get; set; }
        public virtual ICollection<SalesDetail> SalesDetails { get; set; }
    }
}