CREATE TABLE [dbo].[Purchase] (
    [PurchaseId]                       INT             IDENTITY (1, 1) NOT NULL,
    [OrganizationId]                   INT             NOT NULL,
    [VendorId]                         INT             NOT NULL,
    [VatChallanNo]                     NVARCHAR (50)   NULL,
    [VatChallanIssueDate]              DATETIME        NULL,
    [VendorInvoiceNo]                  NVARCHAR (50)   NOT NULL,
    [InvoiceNo]                        NVARCHAR (50)   NOT NULL,
    [PurchaseDate]                     DATETIME        NOT NULL,
    [PurchaseTypeId]                   INT             NOT NULL,
    [PurchaseReasonId]                 INT             NOT NULL,
    [NoOfIteams]                       INT             NOT NULL,
    [TotalPriceWithoutVat]             DECIMAL (18, 2) NOT NULL,
    [DiscountOnTotalPrice]             DECIMAL (18, 2) NOT NULL,
    [TotalDiscountOnIndividualProduct] DECIMAL (18, 2) NOT NULL,
    [TotalImportDuty]                  DECIMAL (18, 2) NOT NULL,
    [TotalRegulatoryDuty]              DECIMAL (18, 2) NOT NULL,
    [TotalSupplementaryDuty]           DECIMAL (18, 2) NOT NULL,
    [TotalVAT]                         DECIMAL (18, 2) NOT NULL,
    [TotalAdvanceTax]                  DECIMAL (18, 2) NOT NULL,
    [TotalAdvanceIncomeTax]            DECIMAL (18, 2) NOT NULL,
    [IsVatDeductedInSource]            BIT             NOT NULL,
    [PayableAmount]                    AS              (CONVERT([decimal](21,2),case when [IsVatDeductedInSource]=(1) then [TotalPriceWithoutVat]-[DiscountOnTotalPrice] else ([TotalPriceWithoutVat]+[TotalVAT])-[DiscountOnTotalPrice] end)),
    [PaidAmount]                       DECIMAL (18, 2) NULL,
    [DueAmount]                        AS              (CONVERT([decimal](21,2),case when [IsVatDeductedInSource]=(1) then [TotalPriceWithoutVat]-[DiscountOnTotalPrice] else ([TotalPriceWithoutVat]+[TotalVAT])-[DiscountOnTotalPrice] end)-[PaidAmount]),
    [ExpectedDeliveryDate]             DATETIME        NULL,
    [DeliveryDate]                     DATETIME        NULL,
    [LcNo]                             NVARCHAR (50)   NULL,
    [LcDate]                           DATETIME        NULL,
    [BillOfEntry]                      NVARCHAR (50)   NULL,
    [BillOfEntryDate]                  DATETIME        NULL,
    [DueDate]                          DATETIME        NULL,
    [TermsOfLc]                        NVARCHAR (500)  NULL,
    [PoNumber]                         NVARCHAR (50)   NULL,
    [MushakGenerationId]               INT             NULL,
    [IsComplete]                       BIT             NOT NULL,
    [CreatedBy]                        INT             NULL,
    [CreatedTime]                      DATETIME        NULL,
    CONSTRAINT [PK_Purchase] PRIMARY KEY CLUSTERED ([PurchaseId] ASC),
    CONSTRAINT [FK_Purchase_Organizations] FOREIGN KEY ([OrganizationId]) REFERENCES [dbo].[Organizations] ([OrganizationId]),
    CONSTRAINT [FK_Purchase_PurchaseReason] FOREIGN KEY ([PurchaseReasonId]) REFERENCES [dbo].[PurchaseReason] ([PurchaseReasonId]),
    CONSTRAINT [FK_Purchase_PurchaseTypes] FOREIGN KEY ([PurchaseTypeId]) REFERENCES [dbo].[PurchaseTypes] ([PurchaseTypeId]),
    CONSTRAINT [FK_Purchase_Vendor] FOREIGN KEY ([VendorId]) REFERENCES [dbo].[Vendor] ([VendorId])
);

